require("birkj.lazy")
require("birkj.set")
require("birkj.telescope")
require("birkj.treesitter")
require("birkj.lsp")
require("birkj.cmp")
require("birkj.diagnostic")
require("birkj.harpoon")
-- require("birkj.packer")

